### ISSUE TITLE
Make Connection between processor and remote process group issue

### ISSUE THREAD

**Issue by hamzabekkouri** [Chaffelson/nipyapi#169] opened 2019-12-30 14:14 UTC
* Nipyapi version: last version 
* NiFi version: 1.9
* NiFi-Registry version:
* Python version: 3.7
* Operating System: ubuntu

### Description
I wanna connect processor with remote process group using the API, what I should do in **target** parametre in canvas.create_connection to make connection between both of them. 

Please help me to solve this problème! 

### What I Did
I want to connect those two stuff together : 

![image](https://user-images.githubusercontent.com/30293738/71585379-9ce8d180-2b16-11ea-9866-6967e08f612f.png)

RouteOnAttribute_root = canvas.get_processor("48027b2c-016f-1000-93dc-ced7630e9ffa",identifier_type='id')

rpg__id = "46e9c4df-016f-1000-6eb5-e52138e0a1e3"
**rpg** = canvas.get_remote_process_group(rpg_id=rpg__id,summary=False)
canvas.set_remote_process_group_transmission(rpg, enable=False, refresh=False)

canvas.create_connection(source=RouteOnAttribute_root,target=**rpg** ,relationships=['unmatched'])

### Urgency

Please give a brief description of how critical this issue is to you.  
For example, if it's blocking your Production environment, or perhaps you are just notifying us of something you found but isn't blocking your workflow.

**Comment by ekovacs** [comment] 2020-01-03 14:12
hi @hamzabekkouri,
i think this is a duplicate of my original report:
https://github.com/Chaffelson/nipyapi/issues/165

meanwhile i opted for creating the flow on the nifi UI, saved and downloaded as a template,

and then used that template through the nipyapi.

**Comment by Chaffelson** [comment] 2020-06-21 14:26
I'm going to close this issue and we will continue to address it in #165

**Closed by Chaffelson** 2020-06-21 14:26 UTC
